# Generated by Django 4.2 on 2023-07-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0010_image_portofolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='Alamat default', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='art_category',
            field=models.CharField(choices=[('ST', 'Seni Tari'), ('STR', 'Seni Teater'), ('SM', 'Seni Musik'), ('SR', 'Seni Rupa')], default='ST', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='+62', max_length=15),
        ),
        migrations.AddField(
            model_name='contact',
            name='portfolio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
