# Generated by Django 4.2 on 2023-07-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0011_remove_contact_message_remove_contact_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkitem',
            name='asal_budaya',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='jumlah_orang',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='keterangan_budaya',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='lokasi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('ST', 'Seni Tari'), ('STR', 'Seni Teater'), ('SM', 'Seni Musik'), ('SR', 'Seni Rupa')], max_length=5),
        ),
    ]
