# Generated by Django 4.2 on 2023-07-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0012_produkitem_asal_budaya_produkitem_is_popular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='asal_budaya',
            field=models.CharField(choices=[('ST', 'Seni Tari'), ('STR', 'Seni Teater'), ('SM', 'Seni Musik'), ('SR', 'Seni Rupa')], max_length=30),
        ),
    ]
