# Generated by Django 4.2 on 2023-07-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0014_alter_produkitem_asal_budaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkitem',
            name='gambarPorto',
            field=models.ManyToManyField(blank=True, related_name='produk_items', to='toko.image'),
        ),
        migrations.DeleteModel(
            name='Portofolio',
        ),
    ]
