# Generated by Django 4.2 on 2023-07-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0015_produkitem_gambarporto_delete_portofolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkitem',
            name='gambarPorto',
        ),
        migrations.CreateModel(
            name='Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('images', models.ManyToManyField(blank=True, related_name='portofolios', to='toko.image')),
                ('produk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.produkitem')),
            ],
        ),
    ]
