# Generated by Django 4.2 on 2023-07-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0016_remove_produkitem_gambarporto_portofolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='images',
            field=models.ManyToManyField(related_name='portofolios', to='toko.image'),
        ),
    ]
