# Generated by Django 4.2 on 2023-07-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0017_alter_portofolio_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portofolio',
            name='images',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='produk_item',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Portofolio',
        ),
    ]
