# Generated by Django 4.2 on 2023-07-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0018_remove_portofolio_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkitem',
            name='is_recomend',
            field=models.BooleanField(default=False),
        ),
    ]
