# Generated by Django 4.2 on 2023-07-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0019_produkitem_is_recomend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkitem',
            old_name='is_recomend',
            new_name='is_recomended',
        ),
    ]
