# Generated by Django 4.2 on 2023-07-28 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0020_rename_is_recomend_produkitem_is_recomended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_category', models.CharField(max_length=5, unique=True)),
                ('nama_category', models.CharField(max_length=100)),
                ('banner_category', models.ImageField(upload_to='category_banners')),
                ('desc_category', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toko.category'),
        ),
    ]
