# Generated by Django 4.2 on 2023-07-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0021_category_alter_produkitem_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_asal_budaya', models.CharField(max_length=100)),
                ('code_budaya', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='asal_budaya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toko.culturalorigin'),
        ),
    ]
