# Generated by Django 4.2 on 2023-07-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0022_culturalorigin_alter_produkitem_asal_budaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkitem',
            name='banner_history_prod',
            field=models.ImageField(blank=True, null=True, upload_to='product_detail_banners'),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='current_stok',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='desc_history_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='desc_history_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='desc_history_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='main_banner_detail',
            field=models.ImageField(blank=True, null=True, upload_to='product_banners'),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='max_stok',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='jumlah_orang',
            field=models.TextField(blank=True, null=True),
        ),
    ]
