# Generated by Django 4.2 on 2023-07-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0023_produkitem_banner_history_prod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkitem',
            name='keterangan_budaya',
        ),
        migrations.AddField(
            model_name='produkitem',
            name='gambar_detail',
            field=models.ImageField(blank=True, null=True, upload_to='product_detail'),
        ),
    ]
